### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#17] opened 2020-06-24 13:51 UTC
java.lang.ArrayIndexOutOfBoundsException: 131079
	at net.simpleguide.game.serflings.j.a.z.a(net.simpleguide.Main:3392)
	at net.simpleguide.game.serflings.j.a.A.a(net.simpleguide.Main:3343)
	at net.simpleguide.game.serflings.j.a.k.a(net.simpleguide.Main:354)
	at net.simpleguide.game.serflings.j.a.z.a(net.simpleguide.Main:3339)
	at net.simpleguide.game.serflings.j.a.h.b(net.simpleguide.Main:852)
	at net.simpleguide.game.serflings.a.a(net.simpleguide.Main:26994)
	at net.simpleguide.game.serflings.n.d(net.simpleguide.Main:416)
	at net.simpleguide.a.a.a.run(net.simpleguide.Main:1281)
	at java.lang.Thread.run(Thread.java:748)

Neueste Version: 0.23.0-SNAPSHOT vom 23. Juni 2020 (Changelog)

**Comment by nicymike** [comment] 2020-06-24 18:59
What did you do to get this crash?

**Comment by Spikeone** [comment] 2020-06-24 20:30
Sadly I can't remember. I just started up a game, random map with AI players. I placed some building sites like a sawmill, quarry, watchtower, woodcutter and connected some roads. Can't think of something special.

**Comment by nicymike** [comment] 2020-06-24 21:04
Regarding the stacktrace, the bug has something to do with sending a settler to a road with an invalid building. Maybe there is a bug in the code for building. I need to do some checks.

**Comment by nicymike** [comment] 2020-07-04 09:15
I think I found the cause of this bug in the code of computer building roads. It will be fixed in the final version.

**Closed** 2020-07-07 16:18 UTC
Labels: bug
