### ISSUE TITLE
[Issue] Sound cracking

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#5] opened 2020-01-03 17:27 UTC
When enabling sound effects, after some time you will hear a lot of cracks. When shortly disabling the sound, then this cracking is gone.

**Comment by nicymike** [comment] 2020-01-07 09:24
What do you mean by cracks? I know of a problem with the sounds of the sawmills which will go crazy if you have many of them.

**Comment by Spikeone** [comment] 2020-01-07 21:50
Either it was the sound of 2 sawmills or it was multiplayer related as well. Other than the sawmill sound I can't reproduce in singleplayer.

**Comment by Spikeone** [comment] 2020-02-09 11:14
In multiplayer I had the same issue with the iron smelter

**Comment by nicymike** [comment] 2020-08-14 19:08
The crack in the sound for smelting is also present in the original game so I guess it is not an easy fix.

**Comment by Spikeone** [comment] 2020-09-04 13:29
Which is strange as it seems to only appear after some time :-/

**Comment by nicymike** [comment] 2020-09-04 16:21
Do you know which sound has the cracking?

**Comment by Spikeone** [comment] 2020-09-04 17:34
Pretty certain it was the smelter

**Comment by nicymike** [comment] 2021-06-05 11:47
I rebuilt the whole sound processing in the newest snapshot of version 1.0. Please check if the problem is solved now.

**Comment by Spikeone** [comment] 2021-07-08 07:50
@nicymike I guess it's fixed but as you may have heard in my stream, the sound effects are still somewhat annyoing in some cases - but guess thats just the way it was in the original, was it?

**Comment by nicymike** [comment] 2021-07-08 13:40
I did a check on the original game and the sounds of three blacksmiths are the same as in Serflings. The 2x game speed also speeds up the sounds.

The sounds are limited to four sounds per tick which are selected by sound priorities. The blacksmith has a rather high priority so it dominates the other sounds.

I guess we can close this issue.

**Closed** 2023-02-21 16:00 UTC
Labels: bug

**Comment by Wakeboardtiger** [comment] 2023-07-14 04:18
Hallo, just checked in the serflings 2.0.0. The sound cracking for the Iron/Gold smelters are still there and something else I noticed: The hacking sound of the mines are totally synchronized in serflings, while in the orig. its way more random if you have a lot of them working at the same time on the screen. So maybe something wrong with the timing or the length of the sound sample of the miners? The sounds a way nicer to endure in the orig. 
Maybe there was also a limitation in the orig. how many samples could play at the same time, which makes the whole sound a bit better?

**Comment by nicymike** [comment] 2023-07-17 14:18
Thank you, i will check this.

**Comment by Wakeboardtiger** [comment] 2025-12-11 05:59
Hello, I just checked, cracking with the melters still there, so I asked chatgtp to help me to put the observation together with a possible solution, I hope thats ok:

1. Melter sound has a constant crack/pop

The melter sound always produces a noticeable crack even when only one melter is active.
This means it’s not related to overlapping sound events, but likely to how the sample is decoded or played.

Likely causes:

incorrect PCM decoding from SPAE.PA / SPAD.PA
(wrong signed/unsigned interpretation, sample rate, bit depth, or block alignment)

missing small fade-in/out envelope (original game likely used a soft attack, Serflings plays raw waveform → pop)

off-by-one sample start (beginning mid-wave → click)

Java/OpenAL reinitialises or resamples the buffer → trigger pop

Expected:

In the original game the melter sound plays cleanly with no crack.

Suggested fixes:

verify decoded waveform against the original

add a tiny 2–5 ms fade-in to the start of short SFX

confirm correct PCM format and block alignment

avoid reinitialising new Clip instances for every sound (use pooling)

2. Mining sound timing is incorrect when multiple miners work

When several miners are active at once, Serflings starts all mining sound samples at exactly the same time.
In the original Settlers the mining sounds were slightly offset and not fully synchronized, creating a more natural and less repetitive soundscape.

Likely cause:

identical trigger timing with no random jitter

original engine introduced natural variation through game ticks or random offsets

Expected:

Multiple miners should not sound identical or perfectly synchronized.

Suggested fix:

introduce a small random offset (ca. 10–25 ms) when multiple identical SFX trigger at the same time
→ makes the mix more natural and matches original behaviour

**Comment by nicymike** [comment] 2025-12-11 17:10
1. Regarding the crack for the smelter:
The crack does also exist in the original game if I check with dosbox but it is softer and therefor not so clear to recognize. I guess I need to cut off the beginning.
If you want to analyse the wav file, you may add the parameter --extract-data in the console.

2. The sounds are bound to a specific animation timer and will be played on render. There might be a bug inside the code but I have to check the original Assembler to verify this. The random offset is difficult to add because this could break the calculation for the timer.

**Comment by Wakeboardtiger** [comment] 2025-12-11 17:24
I see, well thanks for looking into it anyway...
